### ISSUE TITLE
write simple FI json list

### ISSUE THREAD

**Issue by feomike** [feomike/slope#10]
get a json file with the list of bank names.   doing an autocomplete on the bank (the who) input.
something like:
{
    "banks": [
        "Bank One",
        "Bank Two",
        "Bank Two Inc." 
    ]
}

place in the /data dir

**Comment by feomike** [comment]
holding off on this on as names are hard;  need to add in respondent_id and agency_code (perhaps).

**Comment by feomike** [comment]
simple part of this executed.  it creates a dump file of the names run at the time of running.  the problem w/ this is it would over write this file if ever this was run multiple times.  for this simple case (proof) it is good enough for now.  closing

**Comment by feomike** [comment]
change "financial institution names" tp ""financial_institution_names""

**Comment by awolfe76** [comment]
@feomike any objections to using camelCase everywhere?
So `financialInstituionNames` instead. Just makes it even easier to deal with.

**Comment by feomike** [comment]
no objections @awolfe76.  easy peasy

**Comment by feomike** [comment]
@wolfe76 - like this?  

{
    "financialInstitutionNames": ["first-national-bank-alaska", "golden", "golden-one", "quicken", "quicken-loans", "the-golden-1-credit-union"]
}

**Comment by awolfe76** [comment]
:+1:

**Comment by feomike** [comment]
done

**Comment by awolfe76** [comment]
Sorry, just noticed that the bank names here have `-`. We should use the "clean" name.
For example, instead of `"quicken-loans"` it should be `"Quicken Loans"`.
