### ISSUE TITLE
Clean up json metadata

### ISSUE THREAD

**Issue by awolfe76** [feomike/slope#27]
### Current

Currently file looks like (data shortened to highlight metadata):

``` json
{
    "layout": "bank-data",
    "description": "Bank Data",
    "title": "Financial Institution HMDA filings",
    "bank": "Quicken Loans",
    "type": "line",
    "categories": "chart",
    "data": {
        "years": [{
            "count": 0,
            "loan_amount": 0,
            "year": "1990"
        }]
    }
}
```
### Remove

We can remove `layout`, `description`, `title` and `categories` for sure.
We can _probably_ remove `type` as well. For now these are all line charts. Later, if needed, we could reintroduce that field.
### Add

We should add a `loanType` and a `location`. These are already known through the directory structure, but would be useful here as well to anyone just viewing a file.
### Result

``` json
{
    "bank": "Quicken Loans",
    "loanType": "Single Family Origination",
    "location": "MD",
    "data": {
        "years": [{
            "count": 0,
            "loan_amount": 0,
            "year": "1990"
        }]
    }
}
```

**Comment by feomike** [comment]
done (might need minor clean up), but basically there.
